
language: python

matrix:
 fast_finish: true
 include:
  - python: "2.7"
    env: NETWORKX_VERSION=networkx==1.9
  - python: "2.7"
    env: NETWORKX_VERSION=networkx==1.8
  - python: "2.7"
    env: NETWORKX_VERSION=networkx==1.4
  - python: "3.3"
    env: NETWORKX_VERSION=networkx==1.9
  - python: "3.4"
    env: NETWORKX_VERSION=networkx==1.9
# allow_failures:
  - python: "2.7"
    env: NETWORKX_VERSION=git+http://github.com/networkx/networkx.git#egg=networkx

install:
 - pip install $NETWORKX_VERSION
 - python setup.py install
script:
 - xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" python ./networkx_viewer/tests.py
