import networkx as nx
from networkx_viewer import Viewer
G = nx.DiGraph()
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
G.add_edge('vold','vold')
app = Viewer(G)
app.mainloop()