import networkx as nx
from networkx_viewer import Viewer
G = nx.DiGraph()
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('epmd','epmd')
G.add_edge('init_shell','epmd')
G.edge['init_shell']['epmd']['read-write'] = '* >read'
G.add_edge('init_shell','epmd')
G.edge['init_shell']['epmd']['read-write'] = '* >search'
G.add_edge('itsonbs','epmd')
G.edge['itsonbs']['epmd']['read-write'] = '* >read'
G.add_edge('itsonbs','epmd')
G.edge['itsonbs']['epmd']['read-write'] = '* >search'
G.add_edge('mfgloader','epmd')
G.edge['mfgloader']['epmd']['read-write'] = '* >search'
G.add_edge('system_server','epmd')
G.edge['system_server']['epmd']['read-write'] = '* >search'
app = Viewer(G)
app.mainloop()