import networkx as nx
from networkx_viewer import Viewer
G = nx.DiGraph()
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
G.add_edge('untrusteddomain','untrusteddomain')
app = Viewer(G)
app.mainloop()