import networkx as nx
from networkx_viewer import Viewer
G = nx.DiGraph()
G.add_edge('appdomain','appdomain')
G.edge['appdomain']['appdomain']['write-read'] = '[open open][write read][append read][open open][write read][append read][open open][write read][append read][open open][write read][append read][open open][write read][append read][open open][write read][append read][write read][open open][write read][append read][open open][write read][append read][write read][setattr getattr][write read][append read][setopt getopt][write read][open open][write read][append read][write read][write read][append read][write read][open open][setattr getattr][write read][add_name search][remove_name search][setattr getattr][write read][append read][setopt getopt][open open][write read][append read][open open][setattr getattr][open execmod][write read][open open][open open][write read][append read][append read][open open][open open][write read][append read][append read][open open][write read][append read][open open][write read][append read][write read][write read][write read][write read][setopt getopt][setopt getopt][open open][setattr getattr][open execmod][write read][write read][open open][setattr getattr][write read][append read][write read][open open][write read][append read][open open][write read][append read][open open][setattr getattr][write read][add_name search][remove_name search][open open][write read][add_name search][add_name search][open open][write read][add_name search][remove_name search][open open][setattr getattr][write read][append read][write read][open open][write read][append read][open open][write read][append read][write read][setopt getopt][open open][write read][append read][write read][open open][write read][append read][write read][write read][append read][write read][setattr getattr][setopt getopt][open open][setattr getattr][write read][append read][open open]'
G.add_edge('appdomain','trusteddomain')
G.edge['appdomain']['trusteddomain']['write-read'] = '[open open]'
G.add_edge('appdomain','appdomain')
G.edge['appdomain']['appdomain']['write-read'] = '[open open][write read][append read][open open][write read][append read][open open][write read][append read][open open][write read][append read][open open][write read][append read][open open][write read][append read][write read][open open][write read][append read][open open][write read][append read][write read][setattr getattr][write read][append read][setopt getopt][write read][open open][write read][append read][write read][write read][append read][write read][open open][setattr getattr][write read][add_name search][remove_name search][setattr getattr][write read][append read][setopt getopt][open open][write read][append read][open open][setattr getattr][open execmod][write read][open open][open open][write read][append read][append read][open open][open open][write read][append read][append read][open open][write read][append read][open open][write read][append read][write read][write read][write read][write read][setopt getopt][setopt getopt][open open][setattr getattr][open execmod][write read][write read][open open][setattr getattr][write read][append read][write read][open open][write read][append read][open open][write read][append read][open open][setattr getattr][write read][add_name search][remove_name search][open open][write read][add_name search][add_name search][open open][write read][add_name search][remove_name search][open open][setattr getattr][write read][append read][write read][open open][write read][append read][open open][write read][append read][write read][setopt getopt][open open][write read][append read][write read][open open][write read][append read][write read][write read][append read][write read][setattr getattr][setopt getopt][open open][setattr getattr][write read][append read][open open][write read]'
G.edge['appdomain']['appdomain']['fill'] = 'red'
G.add_edge('appdomain','appdomain')
G.edge['appdomain']['appdomain']['write-read'] = '[open open][write read][append read][open open][write read][append read][open open][write read][append read][open open][write read][append read][open open][write read][append read][open open][write read][append read][write read][open open][write read][append read][open open][write read][append read][write read][setattr getattr][write read][append read][setopt getopt][write read][open open][write read][append read][write read][write read][append read][write read][open open][setattr getattr][write read][add_name search][remove_name search][setattr getattr][write read][append read][setopt getopt][open open][write read][append read][open open][setattr getattr][open execmod][write read][open open][open open][write read][append read][append read][open open][open open][write read][append read][append read][open open][write read][append read][open open][write read][append read][write read][write read][write read][write read][setopt getopt][setopt getopt][open open][setattr getattr][open execmod][write read][write read][open open][setattr getattr][write read][append read][write read][open open][write read][append read][open open][write read][append read][open open][setattr getattr][write read][add_name search][remove_name search][open open][write read][add_name search][add_name search][open open][write read][add_name search][remove_name search][open open][setattr getattr][write read][append read][write read][open open][write read][append read][open open][write read][append read][write read][setopt getopt][open open][write read][append read][write read][open open][write read][append read][write read][write read][append read][write read][setattr getattr][setopt getopt][open open][setattr getattr][write read][append read][open open][write read][append read]'
G.add_edge('appdomain','trusteddomain')
G.edge['appdomain']['trusteddomain']['write-read'] = '[open open][write read]'
G.edge['appdomain']['trusteddomain']['fill'] = 'red'
G.add_edge('appdomain','trusteddomain')
G.edge['appdomain']['trusteddomain']['write-read'] = '[open open][write read][append read]'
G.add_edge('trusteddomain','appdomain')
G.edge['trusteddomain']['appdomain']['write-read'] = '[open open]'
G.add_edge('trusteddomain','trusteddomain')
G.edge['trusteddomain']['trusteddomain']['write-read'] = '[setattr getattr][write read][append read][setopt getopt][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][setattr getattr][write read][append read][setopt getopt][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][write read][unix_write unix_read][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][write read][unix_write unix_read][open open]'
G.add_edge('trusteddomain','appdomain')
G.edge['trusteddomain']['appdomain']['write-read'] = '[open open][write read]'
G.edge['trusteddomain']['appdomain']['fill'] = 'red'
G.add_edge('trusteddomain','appdomain')
G.edge['trusteddomain']['appdomain']['write-read'] = '[open open][write read][append read]'
G.add_edge('trusteddomain','trusteddomain')
G.edge['trusteddomain']['trusteddomain']['write-read'] = '[setattr getattr][write read][append read][setopt getopt][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][setattr getattr][write read][append read][setopt getopt][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][write read][unix_write unix_read][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][write read][unix_write unix_read][open open][write read]'
G.edge['trusteddomain']['trusteddomain']['fill'] = 'red'
G.add_edge('trusteddomain','trusteddomain')
G.edge['trusteddomain']['trusteddomain']['write-read'] = '[setattr getattr][write read][append read][setopt getopt][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][setattr getattr][write read][append read][setopt getopt][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][write read][unix_write unix_read][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][setattr getattr][write read][append read][setopt getopt][write read][unix_write unix_read][write read][unix_write unix_read][open open][write read][append read]'
app = Viewer(G)
app.mainloop()