import networkx as nx
from networkx_viewer import Viewer
G = nx.DiGraph()
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
G.add_edge('device_domain','device_domain')
app = Viewer(G)
app.mainloop()