import networkx as nx
from networkx_viewer import Viewer
G = nx.DiGraph()
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
G.add_edge('dhcp','dhcp')
app = Viewer(G)
app.mainloop()