import networkx as nx
from networkx_viewer import Viewer
G = nx.DiGraph()
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
G.add_edge('domain','domain')
app = Viewer(G)
app.mainloop()