import networkx as nx
from networkx_viewer import Viewer
G = nx.DiGraph()
G.add_edge('appdomain','appdomain')
G.edge['appdomain']['appdomain']['write-read'] = '[open open][write read][append read][open open][write read][append read][open open][write read][append read][open open][write read][append read][open open][write read][append read][open open][write read][append read][write read][open open][write read][append read][open open][write read][append read][write read][setattr getattr][write read][append read][setopt getopt][write read][open open][write read][append read][write read][write read][append read][write read][open open][setattr getattr][write read][add_name search][remove_name search][setattr getattr][write read][append read][setopt getopt][open open][write read][append read][open open][setattr getattr][open execmod][write read][open open][open open][write read][append read][append read][open open][open open][write read][append read][append read][open open][write read][append read][open open][write read][append read][write read][write read][write read][write read][setopt getopt][setopt getopt][open open][setattr getattr][open execmod][write read]'
G.edge['appdomain']['appdomain']['fill'] = 'red'
G.add_edge('appdomain','fixmo_app')
G.edge['appdomain']['fixmo_app']['write-read'] = '[open open][append read][open open][setattr getattr][open execmod][open open][append read][open open][append read][write read][write read][setopt getopt][open open][setattr getattr][open execmod][write read]'
G.edge['appdomain']['fixmo_app']['fill'] = 'red'
G.add_edge('appdomain','good_app')
G.edge['appdomain']['good_app']['write-read'] = '[open open][append read][open open][setattr getattr][open execmod][open open][append read][open open][append read][write read][write read][setopt getopt][open open][setattr getattr][open execmod][write read]'
G.edge['appdomain']['good_app']['fill'] = 'red'
G.add_edge('appdomain','gpsd')
G.edge['appdomain']['gpsd']['write-read'] = '[open open][open open][setattr getattr][write read][write read][add_name search][remove_name search][add_name search][remove_name search][open open][open open][open execmod][open execmod][write read]'
G.edge['appdomain']['gpsd']['fill'] = 'red'
G.add_edge('appdomain','gsiff_daemon')
G.edge['appdomain']['gsiff_daemon']['write-read'] = '[open open][write read][add_name search][remove_name search][write read]'
G.edge['appdomain']['gsiff_daemon']['fill'] = 'red'
G.add_edge('appdomain','mediaserver')
G.edge['appdomain']['mediaserver']['write-read'] = '[open open][write read][append read][open open][open open][setattr getattr][write read][append read][write read][append read][open open][setattr getattr][write read][add_name search][remove_name search][write read][append read][open open][setattr getattr][write read][append read][open open][setattr getattr][write read][add_name search][remove_name search][open open][setattr getattr][write read][add_name search][remove_name search][open open][open execmod][write read]'
G.edge['appdomain']['mediaserver']['fill'] = 'red'
G.add_edge('appdomain','vmware_app')
G.edge['appdomain']['vmware_app']['read-write'] = '* >read'
G.add_edge('fixmo_app','appdomain')
G.edge['fixmo_app']['appdomain']['write-read'] = '[write read][open open][setattr getattr][open execmod][open open][open open][write read][write read][setopt getopt][setopt getopt][open open][setattr getattr][open execmod][write read]'
G.edge['fixmo_app']['appdomain']['fill'] = 'red'
G.add_edge('fixmo_app','fixmo_app')
G.edge['fixmo_app']['fixmo_app']['write-read'] = '[write read][setopt getopt][write read][setopt getopt][open open][write read][append read][setattr getattr][write read][append read][setopt getopt][open open][setattr getattr][write read][add_name search][remove_name search][write read][setopt getopt][write read][setopt getopt][open open][setattr getattr][write read][append read][open open][write read][append read][open open][setattr getattr][write read][append read][open open][write read][append read][open open][write read][append read][write read][setopt getopt][setattr getattr][open open][setattr getattr][write read][append read][open open][write read][append read][open open][write read][setopt getopt][setattr getattr][write read][append read][setopt getopt][open open][setattr getattr][open execmod][open open][write read][setopt getopt][open open][setattr getattr][open execmod][write read]'
G.edge['fixmo_app']['fixmo_app']['fill'] = 'red'
G.add_edge('fixmo_app','good_app')
G.edge['fixmo_app']['good_app']['write-read'] = '[write read][setopt getopt][write read][setopt getopt][open open][write read][append read][setattr getattr][write read][append read][setopt getopt][write read][setopt getopt][write read][setopt getopt][open open][write read][append read][open open][write read][append read][open open][write read][append read][add_name search][remove_name search][write read][setopt getopt][open open][write read][append read][open open][write read][setopt getopt][setattr getattr][write read][append read][setopt getopt][open open][setattr getattr][open execmod][open open][write read][setopt getopt][open open][setattr getattr][open execmod][write read]'
G.edge['fixmo_app']['good_app']['fill'] = 'red'
G.add_edge('fixmo_app','gpsd')
G.edge['fixmo_app']['gpsd']['write-read'] = '[open open][open open][setattr getattr][write read][write read][add_name search][remove_name search][add_name search][remove_name search][add_name search][remove_name search][add_name search][remove_name search][open open][open open][setattr getattr][write read][append read][write read][append read][write read]'
G.edge['fixmo_app']['gpsd']['fill'] = 'red'
G.add_edge('fixmo_app','gsiff_daemon')
G.edge['fixmo_app']['gsiff_daemon']['write-read'] = '[open open][write read][add_name search][remove_name search][write read]'
G.edge['fixmo_app']['gsiff_daemon']['fill'] = 'red'
G.add_edge('fixmo_app','mediaserver')
G.edge['fixmo_app']['mediaserver']['write-read'] = '[open open][setattr getattr][write read][add_name search][remove_name search][open open][write read][append read][add_name search][remove_name search][setattr getattr][add_name search][remove_name search][open open][setattr getattr][write read][append read][write read]'
G.edge['fixmo_app']['mediaserver']['fill'] = 'red'
G.add_edge('fixmo_app','vmware_app')
G.edge['fixmo_app']['vmware_app']['read-write'] = '* >read'
G.add_edge('fixmo_app','appdomain')
G.edge['fixmo_app']['appdomain']['write-read'] = '[write read][open open][setattr getattr][open execmod][open open][open open][write read][write read][setopt getopt][setopt getopt][open open][setattr getattr][open execmod][write read][setopt getopt]'
G.add_edge('fixmo_app','fixmo_app')
G.edge['fixmo_app']['fixmo_app']['write-read'] = '[write read][setopt getopt][write read][setopt getopt][open open][write read][append read][setattr getattr][write read][append read][setopt getopt][open open][setattr getattr][write read][add_name search][remove_name search][write read][setopt getopt][write read][setopt getopt][open open][setattr getattr][write read][append read][open open][write read][append read][open open][setattr getattr][write read][append read][open open][write read][append read][open open][write read][append read][write read][setopt getopt][setattr getattr][open open][setattr getattr][write read][append read][open open][write read][append read][open open][write read][setopt getopt][setattr getattr][write read][append read][setopt getopt][open open][setattr getattr][open execmod][open open][write read][setopt getopt][open open][setattr getattr][open execmod][write read][setopt getopt]'
G.add_edge('fixmo_app','good_app')
G.edge['fixmo_app']['good_app']['write-read'] = '[write read][setopt getopt][write read][setopt getopt][open open][write read][append read][setattr getattr][write read][append read][setopt getopt][write read][setopt getopt][write read][setopt getopt][open open][write read][append read][open open][write read][append read][open open][write read][append read][add_name search][remove_name search][write read][setopt getopt][open open][write read][append read][open open][write read][setopt getopt][setattr getattr][write read][append read][setopt getopt][open open][setattr getattr][open execmod][open open][write read][setopt getopt][open open][setattr getattr][open execmod][write read][setopt getopt]'
G.add_edge('fixmo_app','gpsd')
G.edge['fixmo_app']['gpsd']['write-read'] = '[open open][open open][setattr getattr][write read][write read][add_name search][remove_name search][add_name search][remove_name search][add_name search][remove_name search][add_name search][remove_name search][open open][open open][setattr getattr][write read][append read][write read][append read][write read][setopt getopt]'
G.add_edge('fixmo_app','gsiff_daemon')
G.edge['fixmo_app']['gsiff_daemon']['write-read'] = '[open open][write read][add_name search][remove_name search][write read][setopt getopt]'
G.add_edge('fixmo_app','mediaserver')
G.edge['fixmo_app']['mediaserver']['write-read'] = '[open open][setattr getattr][write read][add_name search][remove_name search][open open][write read][append read][add_name search][remove_name search][setattr getattr][add_name search][remove_name search][open open][setattr getattr][write read][append read][write read][setopt getopt]'
G.add_edge('fixmo_app','radio')
G.edge['fixmo_app']['radio']['write-read'] = '[open open][write read][append read][open open][write read][append read][write read][setopt getopt]'
G.add_edge('fixmo_app','vmware_app')
G.edge['fixmo_app']['vmware_app']['read-write'] = '* >getopt'
G.add_edge('good_app','appdomain')
G.edge['good_app']['appdomain']['write-read'] = '[write read][open open][setattr getattr][open execmod][open open][open open][write read][write read][setopt getopt][setopt getopt][open open][setattr getattr][open execmod][write read]'
G.edge['good_app']['appdomain']['fill'] = 'red'
G.add_edge('good_app','fixmo_app')
G.edge['good_app']['fixmo_app']['write-read'] = '[write read][setopt getopt][write read][setopt getopt][open open][write read][append read][setattr getattr][write read][append read][setopt getopt][open open][setattr getattr][write read][add_name search][remove_name search][write read][setopt getopt][write read][setopt getopt][open open][write read][append read][open open][write read][append read][open open][write read][append read][write read][setopt getopt][open open][write read][append read][open open][write read][setopt getopt][setattr getattr][write read][append read][setopt getopt][open open][setattr getattr][open execmod][open open][write read][setopt getopt][open open][setattr getattr][open execmod][write read]'
G.edge['good_app']['fixmo_app']['fill'] = 'red'
G.add_edge('good_app','good_app')
G.edge['good_app']['good_app']['write-read'] = '[write read][setopt getopt][write read][setopt getopt][setattr getattr][write read][append read][setopt getopt][open open][write read][append read][setattr getattr][write read][append read][setopt getopt][write read][setopt getopt][write read][setopt getopt][setattr getattr][write read][append read][setopt getopt][open open][write read][append read][open open][setattr getattr][write read][append read][open open][setattr getattr][write read][add_name search][remove_name search][open open][write read][append read][open open][write read][append read][open open][setattr getattr][write read][add_name search][remove_name search][write read][setopt getopt][open open][setattr getattr][write read][append read][open open][write read][append read][open open][setattr getattr][write read][append read][open open][setattr getattr][write read][append read][open open][write read][setopt getopt][setattr getattr][write read][append read][setopt getopt][open open][setattr getattr][open execmod][open open][write read][setopt getopt][open open][setattr getattr][open execmod][write read]'
G.edge['good_app']['good_app']['fill'] = 'red'
G.add_edge('good_app','gpsd')
G.edge['good_app']['gpsd']['write-read'] = '[open open][open open][setattr getattr][write read][write read][add_name search][remove_name search][add_name search][remove_name search][open open][write read][add_name search][remove_name search][open open][open open][setattr getattr][write read][append read][write read][append read][write read]'
G.edge['good_app']['gpsd']['fill'] = 'red'
G.add_edge('good_app','gsiff_daemon')
G.edge['good_app']['gsiff_daemon']['write-read'] = '[open open][write read][add_name search][remove_name search][write read]'
G.edge['good_app']['gsiff_daemon']['fill'] = 'red'
G.add_edge('good_app','mediaserver')
G.edge['good_app']['mediaserver']['write-read'] = '[open open][setattr getattr][write read][add_name search][remove_name search][setattr getattr][open open][write read][append read][open open][write read][add_name search][remove_name search][setattr getattr][open open][setattr getattr][write read][append read][write read]'
G.edge['good_app']['mediaserver']['fill'] = 'red'
G.add_edge('good_app','vmware_app')
G.edge['good_app']['vmware_app']['read-write'] = '* >read'
G.add_edge('good_app','appdomain')
G.edge['good_app']['appdomain']['write-read'] = '[write read][open open][setattr getattr][open execmod][open open][open open][write read][write read][setopt getopt][setopt getopt][open open][setattr getattr][open execmod][write read][setopt getopt]'
G.add_edge('good_app','fixmo_app')
G.edge['good_app']['fixmo_app']['write-read'] = '[write read][setopt getopt][write read][setopt getopt][open open][write read][append read][setattr getattr][write read][append read][setopt getopt][open open][setattr getattr][write read][add_name search][remove_name search][write read][setopt getopt][write read][setopt getopt][open open][write read][append read][open open][write read][append read][open open][write read][append read][write read][setopt getopt][open open][write read][append read][open open][write read][setopt getopt][setattr getattr][write read][append read][setopt getopt][open open][setattr getattr][open execmod][open open][write read][setopt getopt][open open][setattr getattr][open execmod][write read][setopt getopt]'
G.add_edge('good_app','good_app')
G.edge['good_app']['good_app']['write-read'] = '[write read][setopt getopt][write read][setopt getopt][setattr getattr][write read][append read][setopt getopt][open open][write read][append read][setattr getattr][write read][append read][setopt getopt][write read][setopt getopt][write read][setopt getopt][setattr getattr][write read][append read][setopt getopt][open open][write read][append read][open open][setattr getattr][write read][append read][open open][setattr getattr][write read][add_name search][remove_name search][open open][write read][append read][open open][write read][append read][open open][setattr getattr][write read][add_name search][remove_name search][write read][setopt getopt][open open][setattr getattr][write read][append read][open open][write read][append read][open open][setattr getattr][write read][append read][open open][setattr getattr][write read][append read][open open][write read][setopt getopt][setattr getattr][write read][append read][setopt getopt][open open][setattr getattr][open execmod][open open][write read][setopt getopt][open open][setattr getattr][open execmod][write read][setopt getopt]'
G.add_edge('good_app','gpsd')
G.edge['good_app']['gpsd']['write-read'] = '[open open][open open][setattr getattr][write read][write read][add_name search][remove_name search][add_name search][remove_name search][open open][write read][add_name search][remove_name search][open open][open open][setattr getattr][write read][append read][write read][append read][write read][setopt getopt]'
G.add_edge('good_app','gsiff_daemon')
G.edge['good_app']['gsiff_daemon']['write-read'] = '[open open][write read][add_name search][remove_name search][write read][setopt getopt]'
G.add_edge('good_app','mediaserver')
G.edge['good_app']['mediaserver']['write-read'] = '[open open][setattr getattr][write read][add_name search][remove_name search][setattr getattr][open open][write read][append read][open open][write read][add_name search][remove_name search][setattr getattr][open open][setattr getattr][write read][append read][write read][setopt getopt]'
G.add_edge('good_app','radio')
G.edge['good_app']['radio']['write-read'] = '[open open][write read][append read][open open][write read][append read][write read][setopt getopt]'
G.add_edge('good_app','vmware_app')
G.edge['good_app']['vmware_app']['read-write'] = '* >getopt'
G.add_edge('gpsd','appdomain')
G.edge['gpsd']['appdomain']['write-read'] = '[write read]'
G.edge['gpsd']['appdomain']['fill'] = 'red'
G.add_edge('gpsd','fixmo_app')
G.edge['gpsd']['fixmo_app']['write-read'] = '[write read]'
G.edge['gpsd']['fixmo_app']['fill'] = 'red'
G.add_edge('gpsd','good_app')
G.edge['gpsd']['good_app']['write-read'] = '[open open][setattr getattr][write read][add_name search][remove_name search][write read]'
G.edge['gpsd']['good_app']['fill'] = 'red'
G.add_edge('gpsd','gpsd')
G.edge['gpsd']['gpsd']['write-read'] = '[open open][setattr getattr][write read][append read][write read][open open][open open][setattr getattr][write read][write read][add_name search][remove_name search][add_name search][remove_name search][open open][open open][setattr getattr][write read][write read][add_name search][remove_name search][add_name search][remove_name search][open open][write read][add_name search][remove_name search][open open][write read][append read][open open][write read][append read][open open][write read][add_name search][remove_name search][open open][write read][add_name search][remove_name search][open open][setattr getattr][write read][append read][open open][setattr getattr][write read][append read][open open][open open][setattr getattr][write read][append read][write read][append read][open open][open open][setattr getattr][write read][append read][write read][append read][write read]'
G.edge['gpsd']['gpsd']['fill'] = 'red'
G.add_edge('gpsd','gsiff_daemon')
G.edge['gpsd']['gsiff_daemon']['write-read'] = '[open open][write read][add_name search][remove_name search][open open][write read][add_name search][remove_name search][write read]'
G.edge['gpsd']['gsiff_daemon']['fill'] = 'red'
G.add_edge('gpsd','mediaserver')
G.edge['gpsd']['mediaserver']['write-read'] = '[open open][setattr getattr][write read][add_name search][remove_name search][open open][setattr getattr][write read][add_name search][remove_name search][open open][write read][add_name search][remove_name search][open open][write read][append read][open open][write read][append read][open open][write read][add_name search][remove_name search][open open][setattr getattr][write read][append read][open open][setattr getattr][write read][append read][write read]'
G.edge['gpsd']['mediaserver']['fill'] = 'red'
G.add_edge('gpsd','vmware_app')
G.edge['gpsd']['vmware_app']['read-write'] = '* >read'
G.add_edge('gsiff_daemon','appdomain')
G.edge['gsiff_daemon']['appdomain']['write-read'] = '[write read]'
G.edge['gsiff_daemon']['appdomain']['fill'] = 'red'
G.add_edge('gsiff_daemon','fixmo_app')
G.edge['gsiff_daemon']['fixmo_app']['write-read'] = '[write read]'
G.edge['gsiff_daemon']['fixmo_app']['fill'] = 'red'
G.add_edge('gsiff_daemon','good_app')
G.edge['gsiff_daemon']['good_app']['write-read'] = '[write read]'
G.edge['gsiff_daemon']['good_app']['fill'] = 'red'
G.add_edge('gsiff_daemon','gpsd')
G.edge['gsiff_daemon']['gpsd']['write-read'] = '[open open][open open][add_name search][remove_name search][add_name search][remove_name search][open open][open open][setattr getattr][write read][append read][write read][append read][write read]'
G.edge['gsiff_daemon']['gpsd']['fill'] = 'red'
G.add_edge('gsiff_daemon','gsiff_daemon')
G.edge['gsiff_daemon']['gsiff_daemon']['write-read'] = '[open open][add_name search][remove_name search][open open][add_name search][remove_name search][open open][setattr getattr][write read][append read][write read]'
G.edge['gsiff_daemon']['gsiff_daemon']['fill'] = 'red'
G.add_edge('gsiff_daemon','mediaserver')
G.edge['gsiff_daemon']['mediaserver']['write-read'] = '[open open][add_name search][remove_name search][open open][setattr getattr][write read][append read][write read]'
G.edge['gsiff_daemon']['mediaserver']['fill'] = 'red'
G.add_edge('gsiff_daemon','vmware_app')
G.edge['gsiff_daemon']['vmware_app']['read-write'] = '* >read'
G.add_edge('mediaserver','appdomain')
G.edge['mediaserver']['appdomain']['write-read'] = '[open open][write read][append read][open open][write read][append read][write read][open open][setattr getattr][write read][add_name search][remove_name search][write read]'
G.edge['mediaserver']['appdomain']['fill'] = 'red'
G.add_edge('mediaserver','fixmo_app')
G.edge['mediaserver']['fixmo_app']['write-read'] = '[write read]'
G.edge['mediaserver']['fixmo_app']['fill'] = 'red'
G.add_edge('mediaserver','good_app')
G.edge['mediaserver']['good_app']['write-read'] = '[open open][setattr getattr][write read][add_name search][remove_name search][add_name search][remove_name search][write read]'
G.edge['mediaserver']['good_app']['fill'] = 'red'
G.add_edge('mediaserver','gpsd')
G.edge['mediaserver']['gpsd']['write-read'] = '[open open][open open][setattr getattr][write read][write read][add_name search][remove_name search][add_name search][remove_name search][open open][write read][add_name search][remove_name search][add_name search][remove_name search][open open][write read][append read][open open][write read][append read][open open][write read][add_name search][remove_name search][add_name search][remove_name search][open open][open open][setattr getattr][write read][append read][write read][append read][write read]'
G.edge['mediaserver']['gpsd']['fill'] = 'red'
G.add_edge('mediaserver','gsiff_daemon')
G.edge['mediaserver']['gsiff_daemon']['write-read'] = '[open open][write read][add_name search][remove_name search][write read]'
G.edge['mediaserver']['gsiff_daemon']['fill'] = 'red'
G.add_edge('mediaserver','mediaserver')
G.edge['mediaserver']['mediaserver']['write-read'] = '[open open][setattr getattr][write read][append read][open open][write read][append read][open open][setattr getattr][write read][append read][open open][write read][append read][open open][setattr getattr][write read][add_name search][remove_name search][open open][setattr getattr][write read][append read][open open][open open][setattr getattr][write read][append read][write read][append read][open open][open open][setattr getattr][write read][append read][write read][append read][open open][setattr getattr][write read][add_name search][remove_name search][open open][setattr getattr][write read][add_name search][remove_name search][open open][setattr getattr][write read][add_name search][remove_name search][open open][setattr getattr][write read][add_name search][remove_name search][open open][setattr getattr][write read][add_name search][remove_name search][open open][setattr getattr][write read][append read][open open][write read][add_name search][remove_name search][add_name search][remove_name search][open open][write read][append read][open open][setattr getattr][write read][add_name search][remove_name search][open open][write read][append read][open open][write read][append read][open open][setattr getattr][write read][append read][open open][write read][append read][open open][open open][setattr getattr][write read][append read][write read][append read][open open][write read][add_name search][remove_name search][open open][write read][append read][open open][setattr getattr][write read][append read][open open][setattr getattr][write read][append read][open open][write read][append read][open open][write read][add_name search][remove_name search][open open][setattr getattr][write read][add_name search][remove_name search][open open][setattr getattr][write read][add_name search][remove_name search][open open][write read][append read][open open][write read][add_name search][remove_name search][open open][setattr getattr][write read][append read][open open][setattr getattr][write read][add_name search][remove_name search][open open][write read][add_name search][remove_name search][add_name search][remove_name search][open open][write read][add_name search][remove_name search][open open][setattr getattr][write read][add_name search][remove_name search][open open][setattr getattr][write read][append read][write read][open open][setattr getattr][write read][append read][write read][open open][write read][append read][open open][write read][append read][open open][setattr getattr][write read][append read][open open][write read][append read][write read][open open][setattr getattr][write read][append read][open open][setattr getattr][write read][add_name search][remove_name search][open open][write read][add_name search][remove_name search][write read]'
G.edge['mediaserver']['mediaserver']['fill'] = 'red'
G.add_edge('mediaserver','vmware_app')
G.edge['mediaserver']['vmware_app']['read-write'] = '* >read'
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
G.add_edge('vmware_app','appdomain')
G.add_edge('vmware_app','debuggerd')
G.add_edge('vmware_app','fixmo_app')
G.add_edge('vmware_app','good_app')
G.add_edge('vmware_app','gpsd')
G.add_edge('vmware_app','gsiff_daemon')
G.add_edge('vmware_app','ime_app')
G.add_edge('vmware_app','mediaserver')
G.add_edge('vmware_app','radio')
G.add_edge('vmware_app','s_system_app')
G.add_edge('vmware_app','system_app')
G.add_edge('vmware_app','untrusteddomain')
G.add_edge('vmware_app','vmware_app')
app = Viewer(G)
app.mainloop()